#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Make sure we are in the correct directory
# Otherwise npx will constantly install the required packages for every run
cd $(dirname "$0")/..

npx jira-prepare-commit-msg $1
