trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: BuildBackend
    jobs:
      - template: src/backend/pipeline-template.yml
        parameters:
          workingDirectory: 'src/backend'
          buildConfiguration: 'Release'
          # Uncomment and configure if you want to enable SonarCloud later
          # sonarCloud:
          #   enabled: 'true'
          #   projectKey: 'your-project-key'
          #   projectName: 'your-project-name'
          #   serviceConnection: 'your-sonarcloud-service-connection'
